
export const resourcesAR = {
    SearchHint: "على سبيل المثال: رد الفعل بالطبع",
    Home: "بيت",
    Services: "خدمات",
    Contact: "اتصال",
    About: "عن",
    Submit: "يُقدِّم",
    NewsL: "اشترك في النشرة الإخبارية لدينا للبقاء على اطلاع.",
    Main: "رئيسي",
    Privacy: "خصوصية",
    WebDev: "تطوير الشبكة",
    MobileDev: "تطوير تطبيقات الهاتف المحمول",
    Infra: "بنية تحتية",
    Net: "الشبكات",
    HelpDesk: "مكتب المساعدة",
    FB: "فسبوک",
    ING: "انستاگرام",
    X: "تویتر",
    IN: "لینکت ان",
    WP: "واتساپ",
    YT: "یوتیوب",
    Jobs: "وظائف",
    Partners: "الشركاء",
    Resources: "موارد",
    SocialMedia: "وسائل التواصل الاجتماعي",
    More: "أكثر"
}